services:
  express-ci-cd-practice:
    image: dzyker/express-ci-cd-practice:latest
    ports:
      - "3000:3000"
    restart: always

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
    restart: always
    environment:
      - DOCKER_API_VERSION=1.44
